#!/usr/bin/env bash
set -euo pipefail

# Generates .env.runtime based on CONFIG_PROFILE in .env.
# This lets you switch modes by changing only CONFIG_PROFILE, then restarting compose.
#
# Output: .env.runtime (gitignored)
#
# Supported profiles:
# - demo    (dry-run, mainnet public endpoints; keys optional)
# - live    (live trading, mainnet)
# - testnet (spot sandbox)

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${APP_DIR}/.env"
OUT_FILE="${APP_DIR}/.env.runtime"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: Missing $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

PROFILE="${CONFIG_PROFILE:-demo}"

case "$PROFILE" in
  demo)
    BINANCE_ACTIVE_API_KEY="${BINANCE_DEMO_API_KEY:-}"
    BINANCE_ACTIVE_API_SECRET="${BINANCE_DEMO_API_SECRET:-}"
    BINANCE_SANDBOX="false"
    FREQTRADE_DRY_RUN="true"
    ;;
  live)
    BINANCE_ACTIVE_API_KEY="${BINANCE_LIVE_API_KEY:-}"
    BINANCE_ACTIVE_API_SECRET="${BINANCE_LIVE_API_SECRET:-}"
    BINANCE_SANDBOX="false"
    FREQTRADE_DRY_RUN="false"
    ;;
  testnet)
    BINANCE_ACTIVE_API_KEY="${BINANCE_TESTNET_API_KEY:-}"
    BINANCE_ACTIVE_API_SECRET="${BINANCE_TESTNET_API_SECRET:-}"
    BINANCE_SANDBOX="true"
    FREQTRADE_DRY_RUN="false"
    ;;
  *)
    echo "ERROR: Unknown CONFIG_PROFILE: $PROFILE (expected demo|live|testnet)" >&2
    exit 1
    ;;
esac

# Ensure API server vars exist to avoid compose warnings (still overrideable in .env).
FREQTRADE_API_USERNAME="${FREQTRADE_API_USERNAME:-admin}"
FREQTRADE_API_PASSWORD="${FREQTRADE_API_PASSWORD:-}"
FREQTRADE_API_JWT_SECRET_KEY="${FREQTRADE_API_JWT_SECRET_KEY:-}"
FREQTRADE_API_WS_TOKEN="${FREQTRADE_API_WS_TOKEN:-}"

cat >"$OUT_FILE" <<EOF
# Generated by scripts/sync-runtime-env.sh
CONFIG_PROFILE=${PROFILE}
BINANCE_ACTIVE_API_KEY=${BINANCE_ACTIVE_API_KEY}
BINANCE_ACTIVE_API_SECRET=${BINANCE_ACTIVE_API_SECRET}
BINANCE_SANDBOX=${BINANCE_SANDBOX}
FREQTRADE_DRY_RUN=${FREQTRADE_DRY_RUN}
FREQTRADE_API_USERNAME=${FREQTRADE_API_USERNAME}
FREQTRADE_API_PASSWORD=${FREQTRADE_API_PASSWORD}
FREQTRADE_API_JWT_SECRET_KEY=${FREQTRADE_API_JWT_SECRET_KEY}
FREQTRADE_API_WS_TOKEN=${FREQTRADE_API_WS_TOKEN}
EOF

chmod 600 "$OUT_FILE" 2>/dev/null || true
echo "Wrote ${OUT_FILE} (profile=${PROFILE})"

